import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, CheckCircle2, Loader2, Ticket } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useEffect, useState } from "react";

const API_URL = import.meta.env.VITE_API_URL ?? "";
type Order = { id: string; status: string; totalCents: number; event: { name: string }; items: Array<{ tickets: Array<{ id: string; checkInCode: string; status: string; qrCodeDataUrl: string }> }> };
export default function BuyerOrder() { const [, params] = useRoute("/buyer/orders/:orderId"); const [order, setOrder] = useState<Order | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { const token = localStorage.getItem("digitalticket_access_token") ?? ""; fetch(`${API_URL}/api/v1/orders/${params?.orderId}`, { headers: { Authorization: `Bearer ${token}` } }).then(async (r) => { const data = await r.json(); if (!r.ok) throw new Error(data.error); return data; }).then(setOrder).catch((e) => setError(e.message)); }, [params?.orderId]); if (error) return <main className="grid min-h-screen place-items-center bg-[#f7f5fb] text-center"><div><p className="font-semibold">Pedido indisponível</p><p className="mt-2 text-sm text-slate-500">{error}</p></div></main>; if (!order) return <main className="grid min-h-screen place-items-center bg-[#f7f5fb]"><Loader2 className="h-6 w-6 animate-spin text-fuchsia-500" /></main>; const tickets = order.items.flatMap((item) => item.tickets); return <main className="min-h-screen bg-[#f7f5fb] px-6 py-10 text-slate-950"><div className="mx-auto max-w-3xl"><Link href="/"><span className="inline-flex cursor-pointer items-center gap-2 text-sm text-slate-500"><ArrowLeft className="h-4 w-4" />Voltar</span></Link><div className="mt-8 flex items-center gap-3"><CheckCircle2 className="h-8 w-8 text-emerald-500" /><div><p className="text-sm text-emerald-600">Pedido {order.status}</p><h1 className="text-3xl font-semibold">Seus ingressos</h1></div></div><p className="mt-3 text-slate-500">{order.event.name} · R$ {(order.totalCents / 100).toFixed(2).replace(".", ",")}</p><div className="mt-8 space-y-4">{tickets.map((ticket) => <Card key={ticket.id} className="border-slate-200 bg-white"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Ticket className="h-4 w-4 text-fuchsia-500" />Ingresso digital</CardTitle></CardHeader><CardContent><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-500">Código de entrada</p><p className="mt-1 font-mono text-lg font-semibold tracking-wider">{ticket.checkInCode}</p><p className="mt-2 text-xs text-slate-500">Estado: {ticket.status}</p></div><img src={ticket.qrCodeDataUrl} alt={`QR Code do ingresso ${ticket.checkInCode}`} className="h-24 w-24 rounded-xl" /></div></CardContent></Card>)}</div><Button className="mt-8 bg-slate-950" onClick={() => window.print()}>Imprimir voucher</Button></div></main>; }
