import { CameraView, useCameraPermissions } from "expo-camera";
import { useState } from "react";
import { SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

const API_URL = process.env.EXPO_PUBLIC_API_URL ?? "http://localhost:4000";
const OPERATOR_TOKEN = process.env.EXPO_PUBLIC_OPERATOR_TOKEN ?? "";

export default function App() {
  const [permission, requestPermission] = useCameraPermissions(); const [code, setCode] = useState(""); const [scanned, setScanned] = useState(false); const [message, setMessage] = useState("Aguardando leitura"); const [busy, setBusy] = useState(false); const [result, setResult] = useState<"idle" | "approved" | "used" | "cancelled" | "invalid" | "rejected">("idle");
  const validate = async (candidate: string) => {
    if (!candidate || busy) { if (!candidate) setMessage("Digite ou escaneie um código válido."); return; }
    setBusy(true); setMessage("Validando ingresso no servidor…");
    try {
      const response = await fetch(`${API_URL}/api/v1/check-in/validate`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${OPERATOR_TOKEN}` }, body: JSON.stringify({ code: candidate, consume: true, deviceId: "expo-checkin" }) });
      const data = await response.json(); const state = data.accepted ? "approved" : data.state === "USED" ? "used" : data.state === "CANCELLED" ? "cancelled" : data.state === "INVALID_TOKEN" ? "invalid" : "rejected"; setResult(state); setMessage(data.message ?? (data.accepted ? "Entrada autorizada." : "Entrada recusada."));
    } catch { setResult("rejected"); setMessage("Não foi possível conectar à API de check-in."); } finally { setBusy(false); }
  };
  const handleBarcode = ({ data }: { data: string }) => { if (scanned) return; const normalized = data.replace("digitalticket://ticket/", ""); setScanned(true); setCode(normalized); void validate(normalized); };
  const reset = () => { setScanned(false); setCode(""); setResult("idle"); setMessage("Aguardando leitura"); };
  if (!permission) return <SafeAreaView style={styles.safe}><Text style={styles.subtitle}>Solicitando permissão da câmera…</Text></SafeAreaView>;
  if (!permission.granted) return <SafeAreaView style={styles.safe}><View style={styles.container}><Text style={styles.eyebrow}>DIGITALTICKET / PORTARIA</Text><Text style={styles.title}>A câmera é necessária.</Text><Text style={styles.subtitle}>Permita o acesso para escanear QR Codes de ingressos.</Text><TouchableOpacity style={styles.primary} onPress={requestPermission}><Text style={styles.primaryText}>Permitir câmera</Text></TouchableOpacity></View></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><View style={styles.container}><Text style={styles.eyebrow}>DIGITALTICKET / PORTARIA</Text><Text style={styles.title}>Valide entradas em segundos.</Text><Text style={styles.subtitle}>Aponte a câmera para o QR Code do voucher.</Text><View style={styles.cameraFrame}><CameraView style={StyleSheet.absoluteFillObject} facing="back" onBarcodeScanned={scanned ? undefined : handleBarcode} barcodeScannerSettings={{ barcodeTypes: ["qr"] }} /><View style={styles.scanGuide} /></View><Text style={[styles.statusText, result === "approved" && styles.approved, result !== "idle" && result !== "approved" && styles.rejected]}>{message}</Text>{scanned && <TouchableOpacity style={styles.secondary} onPress={reset}><Text style={styles.secondaryText}>Ler outro ingresso</Text></TouchableOpacity>}<View style={styles.divider}><View style={styles.line} /><Text style={styles.or}>OU DIGITE</Text><View style={styles.line} /></View><TextInput value={code} onChangeText={setCode} placeholder="Ex.: DT-8F3K-29QX" placeholderTextColor="#64748b" style={styles.input} autoCapitalize="characters" /><TouchableOpacity disabled={busy} style={styles.secondary} onPress={() => void validate(code)}><Text style={styles.secondaryText}>{busy ? "Validando…" : "Validar código"}</Text></TouchableOpacity></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#080a12" }, container: { flex: 1, padding: 28, justifyContent: "center" }, eyebrow: { color: "#c084fc", fontSize: 12, letterSpacing: 2, fontWeight: "700" }, title: { color: "#f8fafc", fontSize: 36, lineHeight: 43, fontWeight: "700", marginTop: 18 }, subtitle: { color: "#94a3b8", fontSize: 16, lineHeight: 24, marginTop: 16 }, primary: { backgroundColor: "#d946ef", borderRadius: 16, padding: 18, alignItems: "center", marginTop: 34 }, primaryText: { color: "#fff", fontSize: 16, fontWeight: "700" }, cameraFrame: { height: 230, marginTop: 28, overflow: "hidden", borderRadius: 24, borderWidth: 1, borderColor: "#d946ef", backgroundColor: "#111522" }, scanGuide: { position: "absolute", top: "20%", left: "15%", right: "15%", bottom: "20%", borderWidth: 2, borderColor: "rgba(255,255,255,.8)", borderRadius: 18 }, statusText: { color: "#cbd5e1", textAlign: "center", marginTop: 14, fontSize: 13 }, approved: { color: "#34d399" }, rejected: { color: "#fb7185" }, divider: { flexDirection: "row", alignItems: "center", gap: 12, marginVertical: 20 }, line: { flex: 1, height: 1, backgroundColor: "#1e293b" }, or: { color: "#64748b", fontSize: 11 }, input: { backgroundColor: "#111522", borderRadius: 14, borderWidth: 1, borderColor: "#263044", color: "#f8fafc", padding: 17, fontSize: 16 }, secondary: { borderRadius: 14, borderWidth: 1, borderColor: "#334155", padding: 17, alignItems: "center", marginTop: 12 }, secondaryText: { color: "#e2e8f0", fontSize: 16, fontWeight: "600" } });
